---
- name: Run Python script and save output to file
  hosts: localhost
  tasks:
    - name: Run Python script
      command: python3 /home/cloud/Roles_Infra/inventory/render_yaml.py
      register: script_output

    - name: Save output to file
      copy:
        content: "{{ script_output.stdout }}"
        dest: /home/cloud/Roles_Infra/inventory/host2.yaml


