---
- name: Run Python script and save output to file
  hosts: localhost
  tasks:
    - name: Run Python script
      command: python3 /root/Upgrading_to_Gitlab/dynamic_test/inventory/render_yaml.py
      register: script_output

    - name: Save output to file
      copy:
        content: "{{ script_output.stdout }}"
        dest: /root/Upgrading_to_Gitlab/dynamic_test/inventory/host2.yaml


