- name: Copy JSON file
  copy:
    src: "{{ src_path }}"
    dest: "{{ dest_worker_path }}"

- name: Get JSON file
  slurp:
    src: "{{ dest_worker_path }}"
  register: json_file

- name: Parse JSON file
  set_fact:
    test_cases: "{{ json_file.content | b64decode | from_json }}"

- name: Print variables
  debug:
    var: hostvars[item]['ansible_host']
  loop: "{{ groups['workers'] }}"
  when: hostvars[item]['ansible_host'] == ansible_host

- name: Execute Telnet command to destination IP and port
  shell: |
    for addr in {{ hostvars[item]['destination_ip'].split(',') | replace('[', '') | replace(']', '') | replace(',', '') }}; do
      echo "-------------------------------------------------------------"
      echo -e "Testing connection to ${addr} ..."
      output=$(echo -e "open ${addr} \nwait 1\nquit" | telnet)
      if [[ $output == *Escape* ]]; then
        echo -e "Connection to ${addr} succeeded."
      else
        echo -e "Connection to ${addr} failed"
      fi
      echo "-------------------------------------------------------------"
    done
  loop: "{{ groups['workers'] }}"
  when: hostvars[item]['ansible_host'] == ansible_host
  register: telnet_output

